name: aios
description: "AIOS - On-device AI Agent"
publish_to: 'none'
version: 2.1.19+20119

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  drift: ^2.22.1
  file_picker: ^8.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  llama_cpp_dart: ^0.9.0-dev.6
  open_file: ^3.5.11
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.28
  url_launcher: ^6.3.1
  installed_apps: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0
  sqlite3: ^2.9.4

flutter:
  uses-material-design: true
